spring:
  r2dbc:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    pool:
      max-size: 20
      validation-query: SELECT 1
  sql:
    init:
      mode: never
  rabbitmq:
    username: next-to
    password: saveThem
    virtual-host: /

logging:
  level:
    org.springframework.r2dbc: DEBUG

jwt:
  access-secret: ${ACCESS}
  refresh-secret: ${REFRESH}

coolsms:
  api: ${API}
  secret: ${SECRET}
  sender: ${SEND}
