spring:
  r2dbc:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    pool:
      max-size: 20
      validation-query: SELECT 1
  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.r2dbc: DEBUG

jwt:
  access-secret: ${ACCESS}
  refresh-secret: ${REFRESH}
